import React from "react";
import { AlertTriangle, Info, CheckCircle, ShieldAlert, ArrowRight } from "lucide-react";
import { demoScenario } from "../data/demoScenario";

export const SmartAlerts = ({ currentTheme, onSelectCase }: any) => {
  const getSeverityColor = (severity: string) => {
    switch (severity.toLowerCase()) {
      case "critical": return "border-rose-500/50 bg-rose-500/10 text-rose-500";
      case "high": return "border-orange-500/50 bg-orange-500/10 text-orange-500";
      case "medium": return "border-amber-500/50 bg-amber-500/10 text-amber-500";
      default: return "border-blue-500/50 bg-blue-500/10 text-blue-500";
    }
  };

  const getIcon = (severity: string) => {
    switch (severity.toLowerCase()) {
      case "critical": return <ShieldAlert className="w-5 h-5 text-rose-500" />;
      case "high": return <AlertTriangle className="w-5 h-5 text-orange-500" />;
      case "medium": return <Info className="w-5 h-5 text-amber-500" />;
      default: return <CheckCircle className="w-5 h-5 text-blue-500" />;
    }
  };

  return (
    <div className={`p-6 max-w-7xl mx-auto space-y-6 ${currentTheme.textMain}`}>
      <div className="flex items-center justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold font-sans">Smart Alert Center</h1>
          <p className={`text-sm ${currentTheme.textMuted} mt-1`}>Intelligent investigation alerts generated by KSP Network Analysis</p>
        </div>
        <div className="flex gap-2">
          <select className={`bg-transparent border ${currentTheme.border} rounded-lg px-3 py-1.5 text-xs focus:outline-none focus:ring-1`}>
            <option>All Severities</option>
            <option>Critical</option>
            <option>High</option>
            <option>Medium</option>
          </select>
          <select className={`bg-transparent border ${currentTheme.border} rounded-lg px-3 py-1.5 text-xs focus:outline-none focus:ring-1`}>
            <option>Last 24 Hours</option>
            <option>Last 7 Days</option>
            <option>Last 30 Days</option>
          </select>
        </div>
      </div>

      <div className="grid grid-cols-1 gap-4">
        {demoScenario.alerts.map(alert => (
          <div key={alert.id} className={`flex items-start gap-4 p-5 rounded-2xl border ${currentTheme.border} ${currentTheme.cardBg} shadow-md transition-all hover:shadow-lg`}>
            <div className={`p-2.5 rounded-full border ${getSeverityColor(alert.severity)}`}>
              {getIcon(alert.severity)}
            </div>
            <div className="flex-1">
              <div className="flex justify-between items-start">
                <div>
                  <div className="flex gap-2 items-center mb-1">
                    <span className={`text-[10px] uppercase font-bold tracking-wider px-2 py-0.5 rounded border ${getSeverityColor(alert.severity)}`}>
                      {alert.severity}
                    </span>
                    <span className={`text-[11px] font-mono ${currentTheme.textMuted}`}>{alert.date}</span>
                  </div>
                  <h3 className="text-sm font-bold mt-1.5">{alert.type}</h3>
                  <p className={`text-xs mt-1 leading-relaxed max-w-3xl ${currentTheme.textMuted}`}>{alert.message}</p>
                </div>
                {alert.related_case_id && (
                  <button 
                    onClick={() => {
                      const c = demoScenario.cases.find(c => c.id === alert.related_case_id);
                      if (c && onSelectCase) onSelectCase(c);
                    }}
                    className={`flex items-center gap-1.5 px-3 py-1.5 text-xs font-bold uppercase tracking-wider rounded-lg border transition-all ${currentTheme.id === "dark" ? "border-purple-500/30 text-purple-300 hover:bg-purple-500/10" : "border-purple-300 text-purple-700 hover:bg-purple-50"}`}
                  >
                    View Case <ArrowRight className="w-3.5 h-3.5" />
                  </button>
                )}
              </div>
            </div>
          </div>
        ))}
      </div>
    </div>
  );
};
